services:
  youtube-auto-watch-later:
    build:
      context: https://github.com/Noahffiliation/auto-watch-later.git
      dockerfile: Dockerfile
    container_name: youtube-auto-watch-later
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: no
    # environment:
    #   - INCLUDE_SHORTS=false   # Set to true to include YouTube Shorts, default false
    #   - INCLUDE_TEASERS=false  # Set to true to include teasers and trailers, default false