sonar.projectKey=Noahffiliation_auto_watch_later
sonar.organization=noahffiliation

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/*
sonar.test.exclusions=tests/*
sonar.cpd.exclusions=tests/*
